In [1]:
import pandas as pd

In [2]:
url_2017 = './make_file/2017_seoul_icy_road_accident.csv'
url_2018 = './make_file/2018_seoul_icy_road_accident.csv'

In [3]:
data_2017 = pd.read_csv(url_2017)
data_2018 = pd.read_csv(url_2018)

In [4]:
data_2017

,Unnamed: 0,지역,법정동코드,사고위치
0,1,서울특별시 종로구1,11110001,"[[127.0168137, 37.57307474], [127.01677917, 37..."
1,2,서울특별시 광진구1,11215001,"[[127.07292728, 37.54129396], [127.07289276, 3..."
2,3,서울특별시 강남구1,11680001,"[[127.0354219, 37.49995372], [127.03538738, 37..."
3,4,서울특별시 강서구1,11500001,"[[126.83404835, 37.55924816], [126.83401383, 3..."
4,5,서울특별시 관악구1,11620001,"[[126.95002348, 37.46688152], [126.94998896, 3..."
5,6,서울특별시 노원구1,11350001,"[[127.05992879, 37.66122577], [127.05989427, 3..."
6,7,서울특별시 도봉구1,11320001,"[[127.03753547, 37.65547438], [127.03750095, 3..."
7,8,서울특별시 동대문구1,11230001,"[[127.07161658, 37.56057813], [127.07158206, 3..."
8,9,서울특별시 동작구1,11590001,"[[126.9068623, 37.48507781], [126.90682778, 37..."
9,10,서울특별시 서초구1,11650001,"[[127.02140548, 37.51622068], [127.02137096, 3..."
10,11,서울특별시 성동구1,11200001,"[[127.03076956, 37.54183637], [127.03073504, 3..."
11,12,서울특별시 송파구1,11710001,"[[127.11607347, 37.47836561], [127.11603895, 3..."
12,13,서울특별시 은평구1,11380001,"[[126.92190425, 37.60806035], [126.92186972, 3..."
13,14,서울특별시 중구1,11140001,"[[126.98565558, 37.56615707], [126.98562106, 3..."

In [5]:
import folium
import ast  # 안전한 eval을 위해 ast.literal_eval 사용

def create_map(location_data, year, is_gwangjin): 
    m = folium.Map(location=[37.5665, 126.978], zoom_start=11)  # 서울 전체를 기준으로 지도 초기화

    for idx, entry in location_data.iterrows():
        region = entry['지역']
        
        try:
            # 사고위치 문자열을 안전하게 2차원 배열로 변환
            locations = ast.literal_eval(entry['사고위치'])  
        except:
            print(f"입력 오류: {entry['사고위치']} - 해당 데이터 무시")
            continue  # 오류 발생 시 해당 항목 건너뛰기

        # 사고위치들의 마커를 지도에 추가
        for lon, lat in locations:  # 경도(lon), 위도(lat)로 변경
            folium.Marker([lat, lon]).add_to(m)

        if is_gwangjin : 
            # 광진구일 경우에만 저장하고, 화면에 출력
            if region == '서울특별시 광진구1':
                m.save(f"./make_file/{year}_광진구_사고_밀집_스팟_map.html")  # 광진구 지도만 저장
                print(f"{year}_광진구_사고_밀집_스팟_지도 저장 완료")
    
    if is_gwangjin is False :
        # 모든 구의 사고 위치가 포함된 지도 화면에 출력
        m.save(f"./make_file/{year}_서울시_전체_사고_집중지역_map.html")  # 전체 사고위치 지도 저장
        print(f"{year}_전체 사고위치 지도 저장 완료")

In [6]:
filter_data_2017 = data_2017[data_2017['지역'] == '서울특별시 광진구1']
filter_data_2018 = data_2018[data_2018['지역'] == '서울특별시 광진구1'] 


# 데이터 처리 및 지도 생성
create_map(data_2017, 2017, False)
create_map(data_2018, 2018, False)
create_map(filter_data_2017, 2017, True)
create_map(filter_data_2018, 2018, True)

2017_전체 사고위치 지도 저장 완료
2018_전체 사고위치 지도 저장 완료
2017_광진구_사고_밀집_스팟_지도 저장 완료
2018_광진구_사고_밀집_스팟_지도 저장 완료